# Generated by Django 6.0.5 on 2026-05-27 23:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etiqueta',
            name='tablero',
        ),
        migrations.RemoveField(
            model_name='tarjeta',
            name='etiquetas',
        ),
        migrations.RemoveField(
            model_name='lista',
            name='tablero',
        ),
        migrations.RemoveField(
            model_name='tarjeta',
            name='lista',
        ),
        migrations.RemoveField(
            model_name='tablero',
            name='colaboradores',
        ),
        migrations.RemoveField(
            model_name='tablero',
            name='propietario',
        ),
        migrations.RemoveField(
            model_name='tarjeta',
            name='asignado_a',
        ),
        migrations.AlterModelOptions(
            name='notificacion',
            options={'ordering': ['-creada_en']},
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('colaboradores', models.ManyToManyField(blank=True, related_name='proyectos_compartidos', to=settings.AUTH_USER_MODEL)),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proyectos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('relevamiento', 'Relevamiento'), ('analisis', 'Análisis y Desarrollo'), ('test', 'Test y Capacitación'), ('terminado', 'Terminado')], default='relevamiento', max_length=20)),
                ('categoria', models.CharField(choices=[('tecnico', 'Técnico'), ('funcional', 'Funcional')], default='tecnico', max_length=20)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_limite', models.DateField(blank=True, null=True)),
                ('posicion', models.PositiveIntegerField(default=0)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tareas', to='tareas.proyecto')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tareas_asignadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['estado', 'posicion'],
            },
        ),
        migrations.CreateModel(
            name='ParteHoras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('descripcion', models.CharField(blank=True, max_length=200)),
                ('horas', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('categoria', models.CharField(choices=[('tecnico', 'Técnico'), ('funcional', 'Funcional')], default='tecnico', max_length=20)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partes_horas', to=settings.AUTH_USER_MODEL)),
                ('tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partes_horas', to='tareas.tarea')),
            ],
            options={
                'ordering': ['fecha', 'id'],
            },
        ),
        migrations.DeleteModel(
            name='Comentario',
        ),
        migrations.DeleteModel(
            name='Etiqueta',
        ),
        migrations.DeleteModel(
            name='Lista',
        ),
        migrations.DeleteModel(
            name='Tablero',
        ),
        migrations.DeleteModel(
            name='Tarjeta',
        ),
    ]
